import { and, desc, eq, sql } from 'drizzle-orm';
import type { Rank } from '@/config/enums';
import type { RankSubmissionDiff } from '@/app/schemas/rank-calculator';
import type { RankSubmissionSnapshotV1 } from '@/app/schemas/rank-submission-snapshot';
import { db } from './index';
import {
  playerRankUps,
  players,
  rankSubmissions,
  type RankSubmission,
} from './schema';

export interface CreateRankSubmissionInput {
  /**
   * Generated by the caller, because the Discord announcement links to the
   * submission and is posted before the row exists.
   */
  id: string;
  playerName: string;
  submittedByDiscordId: string;
  rank: Rank;
  previousRank?: Rank | null;
  totalPoints: number;
  discordMessageId: string;
  hasTemplePlayerStats: boolean;
  hasTempleCollectionLog: boolean;
  hasWikiSyncData: boolean;
  isTempleCollectionLogOutdated: boolean;
  snapshot: RankSubmissionSnapshotV1 | Record<string, unknown>;
  diff: RankSubmissionDiff;
}

/** Everything is wrapped in a version envelope on the way in. See `parseSnapshot`. */
export async function createRankSubmission(
  input: CreateRankSubmissionInput,
): Promise<RankSubmission> {
  const [submission] = await db
    .insert(rankSubmissions)
    .values({
      id: input.id,
      playerName: input.playerName,
      submittedByDiscordId: input.submittedByDiscordId,
      rank: input.rank,
      previousRank: input.previousRank ?? null,
      totalPoints: input.totalPoints,
      discordMessageId: input.discordMessageId,
      hasTemplePlayerStats: input.hasTemplePlayerStats,
      hasTempleCollectionLog: input.hasTempleCollectionLog,
      hasWikiSyncData: input.hasWikiSyncData,
      isTempleCollectionLogOutdated: input.isTempleCollectionLogOutdated,
      snapshot: { version: 1, data: input.snapshot },
      diff: { version: 1, data: input.diff },
    })
    .returning();

  return submission;
}

export async function getRankSubmission(
  submissionId: string,
): Promise<RankSubmission | null> {
  const [submission] = await db
    .select()
    .from(rankSubmissions)
    .where(eq(rankSubmissions.id, submissionId))
    .limit(1);

  return submission ?? null;
}

export async function getRankSubmissionsForPlayer(
  playerName: string,
  limit = 20,
): Promise<RankSubmission[]> {
  return db
    .select()
    .from(rankSubmissions)
    .where(eq(rankSubmissions.playerName, playerName))
    .orderBy(desc(rankSubmissions.submittedAt))
    .limit(limit);
}

/**
 * Moves a pending submission to a final state, and returns it.
 *
 * **Claims the row with `FOR UPDATE`**, which is the point. The old check was a
 * plain read of `status !== 'Pending'` followed by a write — two moderators
 * hitting approve within the same second both read "Pending", both proceeded,
 * and both assigned Discord roles. Here the second one blocks until the first
 * commits, then finds the row is no longer pending and gets null.
 *
 * Returns null rather than throwing so the caller can phrase it: "somebody
 * already dealt with this" is not an error, it is a race resolving correctly.
 */
export async function claimRankSubmission(
  submissionId: string,
  outcome: {
    status: 'approved' | 'rejected';
    actionedByDiscordId?: string | null;
    isAutomatic?: boolean;
  },
): Promise<RankSubmission | null> {
  return db.transaction(async (tx) => {
    const [pending] = await tx
      .select()
      .from(rankSubmissions)
      .where(
        and(
          eq(rankSubmissions.id, submissionId),
          eq(rankSubmissions.status, 'pending'),
        ),
      )
      .for('update')
      .limit(1);

    if (!pending) return null;

    const [claimed] = await tx
      .update(rankSubmissions)
      .set({
        status: outcome.status,
        actionedByDiscordId: outcome.actionedByDiscordId ?? null,
        actionedAt: new Date(),
        isAutomatic: outcome.isAutomatic ?? false,
        updatedAt: new Date(),
      })
      .where(eq(rankSubmissions.id, submissionId))
      .returning();

    return claimed;
  });
}

/**
 * Approves a submission and moves the player's rank, in **one** transaction.
 *
 * Order matters and used to be wrong. Approval previously assigned Discord
 * roles, DM'd the member and reacted to the message *before* it had established
 * that this approval was the one that counted — so two moderators clicking
 * within the same second both did all of it. The row is claimed first here, and
 * Discord happens only after this returns.
 *
 * Returns null when the submission was already actioned, which is a race
 * resolving correctly rather than an error.
 */
export async function approveRankSubmission(
  submissionId: string,
  actor: { actionedByDiscordId?: string | null; isAutomatic?: boolean },
): Promise<{ submission: RankSubmission; previousRank: string | null } | null> {
  return db.transaction(async (tx) => {
    const [pending] = await tx
      .select()
      .from(rankSubmissions)
      .where(
        and(
          eq(rankSubmissions.id, submissionId),
          eq(rankSubmissions.status, 'pending'),
        ),
      )
      .for('update')
      .limit(1);

    if (!pending) return null;

    const [claimed] = await tx
      .update(rankSubmissions)
      .set({
        status: 'approved',
        actionedByDiscordId: actor.actionedByDiscordId ?? null,
        actionedAt: new Date(),
        isAutomatic: actor.isAutomatic ?? false,
        updatedAt: new Date(),
      })
      .where(eq(rankSubmissions.id, submissionId))
      .returning();

    const [player] = await tx
      .select()
      .from(players)
      .where(eq(players.playerName, pending.playerName))
      .limit(1);

    const previousRank = player?.rank ?? null;

    // Already at this rank: nothing to move, and no rank-up row worth writing.
    // Not an error — an approval can legitimately be a no-op.
    if (claimed.rank && previousRank !== claimed.rank) {
      await tx.insert(playerRankUps).values({
        playerName: pending.playerName,
        newRank: claimed.rank,
        oldRank: previousRank,
        createdAt: new Date(),
      });

      await tx
        .update(players)
        .set({ rank: claimed.rank })
        .where(eq(players.playerName, pending.playerName));
    }

    return { submission: claimed, previousRank };
  });
}

/** Whether a submission may be auto-approved: every source present and current, and no discrepancy. */
export function isAutoApprovable(
  submission: Pick<
    RankSubmission,
    | 'hasTemplePlayerStats'
    | 'hasTempleCollectionLog'
    | 'hasWikiSyncData'
    | 'isTempleCollectionLogOutdated'
  >,
  diff: RankSubmissionDiff,
): boolean {
  const sourcesComplete =
    submission.hasTemplePlayerStats &&
    submission.hasTempleCollectionLog &&
    submission.hasWikiSyncData &&
    !submission.isTempleCollectionLogOutdated;

  const noDiscrepancy = Object.values(diff).every(
    (value) =>
      value === null ||
      value === undefined ||
      (Array.isArray(value) && value.length === 0) ||
      (typeof value === 'object' && Object.keys(value).length === 0),
  );

  return sourcesComplete && noDiscrepancy;
}

/** Count of submissions still awaiting a moderator, for a queue badge. */
export async function countPendingRankSubmissions(): Promise<number> {
  const [row] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(rankSubmissions)
    .where(eq(rankSubmissions.status, 'pending'));

  return row?.count ?? 0;
}
